package org.firstinspires.ftc.teamcode.UtilOpModes; // This should match the file location. This is auto generated by Android Studio
import com.qualcomm.robotcore.eventloop.opmode.OpMode;
import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import com.pedropathing.follower.Follower;
import org.firstinspires.ftc.teamcode.pedro.Constants;
import com.pedropathing.api.PoseFactory;
import com.pedropathing.math.Pose;
import static com.pedropathing.api.Paths.*;
import com.pedropathing.paths.Path;
import com.pedropathing.ivy.Scheduler;
import static com.pedropathing.ivy.Scheduler.schedule;
import static com.pedropathing.ivy.pedro.PedroCommands.follow;
import com.pedropathing.ivy.Command;
import static com.pedropathing.ivy.groups.Groups.sequential;

@Autonomous
public class FionasAuto extends OpMode
{
    private Follower follower; // Add this
    private final PoseFactory p = PoseFactory.degrees(); // add this
    // our poses
    /*p.of(x, y, heading);
So startPose is at (24, 24) facing 0 degrees, and park is at (48, 48) facing 90 degrees. */
    private final Pose startPose = p.of(24, 24, 0);
    private final Pose scorePose = p.of(48, 48, 90);
    private final Pose parkPose = p.of(72, 48, 90);
    // other poses...


    private final Pose controlPose = p.of(36, 60, 45);

    private Path startToScore() {
        return line(startPose, scorePose).linear(startPose, scorePose);
    }
    private Path park(){
        return line(scorePose, parkPose).linear(scorePose, parkPose);
    }
    private Command autoRoutine() {
        return sequential(
                follow(follower, startToScore()),
                // Add mechanism commands here.
                follow(follower, park())

        );
    }

    @Override
    public void init()
    {
        Scheduler.reset();
        follower = Constants.create(hardwareMap);
        follower.setPose(startPose);
        follower.update();
    }
    @Override
    public void start()
    {
        schedule(autoRoutine());
        // using the same park path from the last page
    }
    @Override
    public void loop()
    {
        follower.update();
        Scheduler.execute();

    }
}
