package org.firstinspires.ftc.teamcode.UtilOpModes; // This should match the file location. This is auto generated by Android Studio
import com.qualcomm.robotcore.eventloop.opmode.OpMode;
import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import com.pedropathing.follower.Follower;
import org.firstinspires.ftc.teamcode.pedro.Constants;
import com.pedropathing.api.PoseFactory;
import com.pedropathing.math.Pose;
import static com.pedropathing.api.Paths.*;
import com.pedropathing.paths.Path;
import com.pedropathing.ivy.Scheduler;
import static com.pedropathing.ivy.Scheduler.schedule;
import static com.pedropathing.ivy.pedro.PedroCommands.follow;
import com.pedropathing.ivy.Command;
import static com.pedropathing.ivy.groups.Groups.sequential;

@Autonomous
public class FionasThing extends OpMode
{
    private Follower follower; // Add this
    private final PoseFactory poseFactory = PoseFactory.degrees(); // add this
    // our poses
    /*p.of(x, y, heading);
So startPose is at (24, 24) facing 0 degrees, and park is at (48, 48) facing 90 degrees. */
    private final Pose start = poseFactory.of(24, 24, 0);
    private final Pose path1Start = poseFactory.of(40, 25, 0);
    private final Pose path1 = poseFactory.of(30, 35, 0);
    private final Pose point2 = poseFactory.of(25, 20, 0);
    private final Pose point3 = poseFactory.of(24, 24, 0);


    public Path path1() {
        return line(path1Start, path1).linear(path1Start, path1);
    }

    public Path path2() {
        return line(path1, point2).linear(path1, point2);
    }

    public Path path3() {
        return line(point2, point3).linear(point2, point3);
    }
    private Command autoRoutine() {
        return sequential(
                follow(follower, path1()),
                follow(follower, path2()),
                follow(follower, path3())

        );
    }

    @Override
    public void init()
    {
        Scheduler.reset();
        follower = Constants.create(hardwareMap);
        follower.setPose(start);
        follower.update();
    }
    @Override
    public void start()
    {
        schedule(autoRoutine());
        // using the same park path from the last page
    }
    @Override
    public void loop()
    {
        follower.update();
        Scheduler.execute();

    }
}
